return {
    "folke/ts-comments.nvim",
    opts = {
        lang = {
            astro = "<!-- %s -->",
            c = "// %s",
            cpp = "// %s",
            css = "/* %s */",
            cue = "// %s",
            c_sharp = "// %s",
            gleam = "// %s",
            glimmer = "{{! %s }}",
            go = "// %s",
            graphql = "# %s",
            handlebars = "{{! %s }}",
            hcl = "# %s",
            html = "<!-- %s -->",
            ini = "; %s",
            javascript = {
                "// %s",
                "/* %s */",
                call_expression = "// %s",
                jsx_attribute = "// %s",
                jsx_element = "{/* %s */}",
                jsx_fragment = "{/* %s */}",
                spread_element = "// %s",
                statement_block = "// %s",
            },
            lua = { "-- %s", "--- %s" }, -- langs can have multiple commentstrings
            php = "// %s",
            rego = "# %s",
            rescript = "// %s",
            ruby = "# %s",
            sql = "-- %s",
            svelte = "<!-- %s -->",
            terraform = "# %s",
            tsx = {
                "// %s",         -- default commentstring when no treesitter node matches
                "/* %s */",      -- will be used for uncommenting
                call_expression = "// %s", -- specific commentstring for call_expression
                jsx_attribute = "// %s",
                jsx_element = "{/* %s */}",
                jsx_fragment = "{/* %s */}",
                spread_element = "// %s",
                statement_block = "// %s",
            },
            twig = "{# %s #}",
            typescript = "// %s",
            vim = '" %s',
            vue = "<!-- %s -->",
        },
    },
    event = "VeryLazy",
    enabled = vim.fn.has("nvim-0.10.0") == 1,
}
