return {
	"NStefan002/screenkey.nvim",
	cmd = "Screenkey",
	version = "*",
	-- config = true,
	opts = {
		win_opts = {
			-- row = vim.o.lines - vim.o.cmdheight - 1,
			row = 1,
			col = vim.o.columns - 1,
			relative = "editor",
			anchor = "NE",
			width = 40,
			height = 3,
			border = "single",
		},
		compress_after = 3,
		clear_after = 3,
		disable = {
			filetypes = {},
			buftypes = {},
		},
		group_mappings = true,
		show_leader = true,

		keys = {
			["<TAB>"] = "󰌒",
			["<CR>"] = "󰌑",
			["<ESC>"] = "Esc",
			["<SPACE>"] = "␣",
			["<BS>"] = "󰌥",
			["<DEL>"] = "Del",
			["<LEFT>"] = "",
			["<RIGHT>"] = "",
			["<UP>"] = "",
			["<DOWN>"] = "",
			["<HOME>"] = "Home",
			["<END>"] = "End",
			["<PAGEUP>"] = "PgUp",
			["<PAGEDOWN>"] = "PgDn",
			["<INSERT>"] = "Ins",
			["<F1>"] = "󱊫",
			["<F2>"] = "󱊬",
			["<F3>"] = "󱊭",
			["<F4>"] = "󱊮",
			["<F5>"] = "󱊯",
			["<F6>"] = "󱊰",
			["<F7>"] = "󱊱",
			["<F8>"] = "󱊲",
			["<F9>"] = "󱊳",
			["<F10>"] = "󱊴",
			["<F11>"] = "󱊵",
			["<F12>"] = "󱊶",
			["CTRL"] = "Ctrl",
			["ALT"] = "Alt",
			["SUPER"] = "󰘳",
		},
	},
}
